import { StreetType, FieldTypes} from "./MonopolyTypes.tsx";

const streets: StreetType[] = [
    {
        type: FieldTypes.STREET,
        id: 1,
        name: "Na Bídě",
        price: 50,
        rent: 2,
        owner: undefined,
        color: "purple",
    },
    {
        type: FieldTypes.STREET,
        id: 2,
        name: "Hodkovická",
        price: 60,
        rent: 4,
        owner: undefined,
        color: "purple",
    },
    {
        type: FieldTypes.STREET,
        id: 3,
        name: "Dr. Milady Horákové",
        price: 70,
        rent: 6,
        owner: undefined,
        color: "purple",
    },
    {
        type: FieldTypes.STREET,
        id: 4,
        name: "Americká",
        price: 80,
        rent: 6,
        owner: undefined,
        color: "light blue",
    },
    {
        type: FieldTypes.STREET,
        id: 5,
        name: "Na Bojišti",
        price: 90,
        rent: 8,
        owner: undefined,
        color: "light blue",
    },
    {
        type: FieldTypes.STREET,
        id: 6,
        name: "Hanychovská",
        price: 100,
        rent: 10,
        owner: undefined,
        color: "light blue",
    },
    {
        type: FieldTypes.STREET,
        id: 7,
        name: "Horská",
        price: 110,
        rent: 10,
        owner: undefined,
        color: "pink",
    },
    {
        type: FieldTypes.STREET,
        id: 8,
        name: "Ruprechtická",
        price: 120,
        rent: 12,
        owner: undefined,
        color: "pink",
    },
    {
        type: FieldTypes.STREET,
        id: 9,
        name: "Vrchlického",
        price: 130,
        rent: 14,
        owner: undefined,
        color: "pink",
    },
    {
        type: FieldTypes.STREET,
        id: 140,
        name: "1. Máje",
        price: 240,
        rent: 14,
        owner: undefined,
        color: "orang",
    },
    {
        type: FieldTypes.STREET,
        id: 11,
        name: "5. Května",
        price: 150,
        rent: 14,
        owner: undefined,
        color: "orange",
    },
    {
        type: FieldTypes.STREET,
        id: 12,
        name: "Masarykova",
        price: 160,
        rent: 14,
        owner: undefined,
        color: "red",
    },
    {
        type: FieldTypes.STREET,
        id: 13,
        name: "Sokolská",
        price: 170,
        rent: 14,
        owner: undefined,
        color: "red",
    },
    {
        type: FieldTypes.STREET,
        id: 14,
        name: "Moskevská",
        price: 180,
        rent: 14,
        owner: undefined,
        color: "yellow",
    },
    {
        type: FieldTypes.STREET,
        id: 15,
        name: "Pražská",
        price: 190,
        rent: 14,
        owner: undefined,
        color: "yellow",
    },
    {
        type: FieldTypes.STREET,
        id: 16,
        name: "Rumunská",
        price: 200,
        rent: 14,
        owner: undefined,
        color: "yellow",
    },
    {
        type: FieldTypes.STREET,
        id: 17,
        name: "Vítězná",
        price: 210,
        rent: 14,
        owner: undefined,
        color: "green",
    },
    {
        type: FieldTypes.STREET,
        id: 18,
        name: "Husova",
        price: 220,
        rent: 14,
        owner: undefined,
        color: "green",
    },
    {
        type: FieldTypes.STREET,
        id: 19,
        name: "Šaldovo náměstí",
        price: 230,
        rent: 14,
        owner: undefined,
        color: "blue",
    },
    {
        type: FieldTypes.STREET,
        id: 20,
        name: "Fügnerova",
        price: 240,
        rent: 14,
        owner: undefined,
        color: "blue",
    },
];